title: COEQWAL Documentation
description: This is a first try on the creation of COEQWAL's data, experiments and results documentation.
theme: just-the-docs

url: coeqwal-test.github.io

aux_links:
  COEQWAL Project Site: https://coeqwal.berkeley.edu/
  
# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

# Changing colors
$link-color: $blue-000;
