title: COEQWAL Documentation
description: This is a first try on the creation of COEQWAL's data, experiments and results documentation.
theme: just-the-docs

url: coeqwal-test.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
